apiVersion: v1alpha1
kind: Setting
metadata:
  name: discourse-plugin-settings
spec:
  forms:
    - group: discourse
      label: Discourse评论设置
      formSchema:
        - $formkit: textarea
          label: Discourse嵌入代码
          name: embedCode
          rows: 10
          help: |
            请粘贴从Discourse管理面板获取的嵌入代码。